# ========================================
# Helm YAML LSP - エラー検出テスト用ワークフロー
# ========================================
#
# このファイルは、診断機能が正しくエラーを検出することを確認するための
# テストファイルです。意図的に以下のエラーを含んでいます：
#
# 【意図的なエラー】
# ❌ 存在しないConfigMap参照: 'missing-configmap'
# ❌ 存在しないSecret参照: 'missing-secret'
# ❌ 存在しないテンプレート参照: 'non-existent-template'
# ❌ 存在しないConfigMapキー参照: 'invalid.key'
#
# 【期待される診断結果】
# - ConfigMap 'missing-configmap' not found (複数箇所)
# - Secret 'missing-secret' not found (複数箇所)
# - Template 'non-existent-template' not found (複数箇所)
# - ConfigMap key 'invalid.key' not found
#
# ========================================

---
# 正常なConfigMap定義（参照されない）
apiVersion: v1
kind: ConfigMap
metadata:
  name: valid-config
  namespace: default
data:
  valid.key: "This ConfigMap is not referenced"

---
# 正常なSecret定義（参照されない）
apiVersion: v1
kind: Secret
metadata:
  name: valid-secret
  namespace: default
type: Opaque
data:
  valid-key: dmFsaWQtdmFsdWU=

---
# 正常なWorkflowTemplate定義
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: error-test-templates
  namespace: default
spec:
  templates:
  - name: valid-template
    container:
      image: busybox:latest
      command: [echo, "This template exists"]

---
# ========================================
# メインワークフロー（エラーを含む）
# ========================================
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: error-test-workflow
  namespace: default
spec:
  entrypoint: error-flow

  templates:
  - name: error-flow
    steps:
    # ❌ エラー1: 存在しないローカルテンプレート参照
    - - name: step1
        template: non-existent-template

    # ❌ エラー2: 存在しないWorkflowTemplate参照
    - - name: step2
        templateRef:
          name: error-test-templates
          template: missing-template

  # ❌ エラー3: 存在しないConfigMap参照（env）
  - name: test-missing-configmap
    container:
      image: busybox:latest
      command: [echo, "test"]
      env:
      - name: TEST_VAR
        valueFrom:
          configMapKeyRef:
            name: missing-configmap
            key: some.key

  # ❌ エラー4: 存在しないSecret参照（env）
  - name: test-missing-secret
    container:
      image: busybox:latest
      command: [echo, "test"]
      env:
      - name: SECRET_VAR
        valueFrom:
          secretKeyRef:
            name: missing-secret
            key: some.key

  # ❌ エラー5: 存在するConfigMapだが存在しないキー参照
  - name: test-invalid-key
    container:
      image: busybox:latest
      command: [echo, "test"]
      env:
      - name: INVALID_VAR
        valueFrom:
          configMapKeyRef:
            name: valid-config
            key: invalid.key

  # ❌ エラー6: 存在しないConfigMap参照（volume）
  volumes:
  - name: missing-config-volume
    configMap:
      name: missing-configmap
  - name: missing-secret-volume
    secret:
      secretName: missing-secret
