# ========================================
# Helm YAML LSP - 全機能デモワークフロー (Plain YAML版)
# ========================================
#
# このファイルは、Phase 5までに実装された全機能を
# 上から順に確認できる包括的なデモファイルです。
#
# 【実装済み機能】
# ✅ Phase 2-3: Argo Workflows基本機能
#    - Definition Provider（定義ジャンプ: F12 / gd）
#    - Hover Provider（ホバー情報表示）
#    - Completion Provider（入力補完: Ctrl+Space）
#    - Diagnostic Provider（エラー検出）
# ✅ Phase 5: ConfigMap/Secret参照サポート
#
# 【動作確認方法】
# 1. VSCode: F5でデバッグ起動、またはNeovimで開く
# 2. 下記の各セクションで動作確認
#    - F12（gd）: 定義へジャンプ
#    - ホバー: 詳細情報表示
#    - 入力時: 補完候補表示
#    - 赤波線: エラー検出
#
# ========================================

---
# ========================================
# Section 1: ConfigMap定義（Phase 5）
# ========================================
# ConfigMapとSecretを定義し、後続のWorkflowから参照します

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  # アプリケーション設定
  app.name: "Demo Application"
  app.version: "1.0.0"

  # 環境設定
  environment: "production"
  log.level: "info"

  # マルチライン設定（| を使用）
  config.yaml: |
    server:
      host: 0.0.0.0
      port: 8080
    database:
      driver: postgres
      pool_size: 10

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
data:
  # Base64エンコードされた機密情報
  # 実際の値: "admin" / "secret123"
  username: YWRtaW4=
  password: c2VjcmV0MTIz
  api-key: ZGVtby1hcGkta2V5LTEyMzQ1Ng==

---
# ========================================
# Section 2: WorkflowTemplate定義（Phase 2）
# ========================================
# 再利用可能なテンプレートを定義します

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: demo-templates
  namespace: default
spec:
  templates:
  # ------------------------------------------
  # 2.1: パラメータを受け取るテンプレート
  # ------------------------------------------
  - name: process-data
    inputs:
      parameters:
      - name: input-data
        description: "処理対象のデータ"
      - name: batch-size
        default: "100"
        description: "バッチサイズ"
    outputs:
      parameters:
      - name: result-count
        valueFrom:
          path: /tmp/count.txt
        description: "処理件数"
    container:
      image: busybox:latest
      command: [sh, -c]
      args:
        - |
          echo "Processing: {{inputs.parameters.input-data}}"
          echo "Batch size: {{inputs.parameters.batch-size}}"
          # ✅ F12: inputs.parametersの定義へジャンプ
          # ✅ ホバー: パラメータの型と説明を表示
          echo "42" > /tmp/count.txt

  # ------------------------------------------
  # 2.2: ConfigMapを参照するテンプレート（Phase 5）
  # ------------------------------------------
  - name: use-configmap
    container:
      image: busybox:latest
      command: [sh, -c]
      args:
        - |
          echo "App: $APP_NAME v$APP_VERSION"
          echo "Environment: $ENVIRONMENT"
          echo "Log Level: $LOG_LEVEL"
      env:
      # ✅ F12 (name): ConfigMap定義へジャンプ
      # ✅ F12 (key): dataキーへジャンプ
      # ✅ ホバー: ConfigMapの内容表示
      - name: APP_NAME
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: app.name
      - name: APP_VERSION
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: app.version
      - name: ENVIRONMENT
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: environment
      - name: LOG_LEVEL
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: log.level

  # ------------------------------------------
  # 2.3: Secretを参照するテンプレート（Phase 5）
  # ------------------------------------------
  - name: use-secrets
    container:
      image: busybox:latest
      command: [sh, -c]
      args:
        - |
          echo "Username: $USERNAME"
          echo "Connecting with credentials..."
      env:
      # ✅ F12: Secret定義へジャンプ
      # ✅ ホバー: Secretの値は[hidden]で隠蔽
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: app-secrets
            key: username
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: app-secrets
            key: password
      - name: API_KEY
        valueFrom:
          secretKeyRef:
            name: app-secrets
            key: api-key

---
# ========================================
# Section 3: メインワークフロー（Phase 2-5統合）
# ========================================

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  # ✅ ホバー: workflow.nameでこの値が参照される
  name: demo-workflow
  namespace: default
spec:
  # ------------------------------------------
  # 3.1: Workflow全体のパラメータ
  # ------------------------------------------
  arguments:
    parameters:
    - name: dataset-name
      value: "customer-data"
      description: "処理対象のデータセット名"
    - name: max-records
      value: "1000"
      description: "最大処理レコード数"

  entrypoint: main-flow

  # ------------------------------------------
  # 3.2: Volume定義（ConfigMap/Secretマウント）
  # ------------------------------------------
  volumes:
  # ✅ F12: ConfigMap定義へジャンプ
  # ✅ ホバー: ConfigMapの内容表示
  - name: config-volume
    configMap:
      name: app-config
  # ✅ F12: Secret定義へジャンプ
  - name: secrets-volume
    secret:
      secretName: app-secrets

  templates:
  # ------------------------------------------
  # 3.3: メインフロー（Steps構造）
  # ------------------------------------------
  - name: main-flow
    steps:
    # Step 1: 初期化
    - - name: initialize
        template: init-step

    # Step 2: データ処理（WorkflowTemplateを参照）
    - - name: process
        # ✅ F12: WorkflowTemplateへジャンプ
        # ✅ ホバー: テンプレートの説明表示
        # ✅ 補完: テンプレート名を補完
        templateRef:
          name: demo-templates
          template: process-data
        arguments:
          parameters:
          # ✅ F12: workflow.parametersの定義へジャンプ
          - name: input-data
            value: "{{workflow.parameters.dataset-name}}"
          - name: batch-size
            value: "50"

    # Step 3: 結果検証
    - - name: validate
        template: validate-step
        arguments:
          parameters:
          # ✅ F12: steps.process.outputsへジャンプ
          # ✅ ホバー: パラメータの型と値を表示
          - name: record-count
            value: "{{steps.process.outputs.parameters.result-count}}"

    # Step 4: ConfigMapとSecretのテスト
    - - name: test-configmap
        # ✅ F12: ローカルテンプレート定義へジャンプ
        templateRef:
          name: demo-templates
          template: use-configmap

      - name: test-secrets
        templateRef:
          name: demo-templates
          template: use-secrets

  # ------------------------------------------
  # 3.4: ローカルテンプレート定義
  # ------------------------------------------
  - name: init-step
    container:
      image: busybox:latest
      command: [sh, -c]
      args:
        - |
          # ✅ ホバー: workflow変数の説明表示
          echo "Workflow Name: {{workflow.name}}"
          echo "Workflow Namespace: {{workflow.namespace}}"
          echo "Workflow UID: {{workflow.uid}}"
          echo "Created at: {{workflow.creationTimestamp}}"
          echo "Dataset: {{workflow.parameters.dataset-name}}"
          echo "Max Records: {{workflow.parameters.max-records}}"
      # Volume マウント
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
      - name: secrets-volume
        mountPath: /etc/secrets

  - name: validate-step
    inputs:
      parameters:
      - name: record-count
        description: "処理されたレコード数"
    container:
      image: busybox:latest
      command: [sh, -c]
      args:
        - |
          COUNT={{inputs.parameters.record-count}}
          MAX={{workflow.parameters.max-records}}
          # ✅ F12: inputs/workflow.parametersへジャンプ

          echo "Processed: $COUNT records"
          echo "Maximum: $MAX records"

          if [ "$COUNT" -gt "$MAX" ]; then
            echo "ERROR: Too many records processed!"
            exit 1
          fi

          echo "Validation: OK"
    # ✅ envFrom: ConfigMap全体を環境変数として読み込み
    envFrom:
    - configMapRef:
        name: app-config

# ========================================
# 動作確認チェックリスト
# ========================================
#
# [ ] Section 1: ConfigMap/Secret
#     - F12: app-config/app-secrets の name にジャンプ
#     - ホバー: data キーの値を表示
#
# [ ] Section 2: WorkflowTemplate
#     - F12: demo-templates の name にジャンプ
#     - F12: inputs.parameters.input-data の定義へジャンプ
#     - ホバー: パラメータの説明表示
#     - F12: configMapKeyRef.name → ConfigMapへジャンプ
#     - F12: configMapKeyRef.key → dataキーへジャンプ
#     - F12: secretKeyRef.name → Secretへジャンプ
#
# [ ] Section 3: メインワークフロー
#     - F12: templateRef.name → WorkflowTemplateへジャンプ
#     - F12: templateRef.template → テンプレート定義へジャンプ
#     - F12: workflow.parameters → argumentsへジャンプ
#     - F12: steps.process.outputs → outputsへジャンプ
#     - ホバー: workflow.* 変数の説明表示
#     - 補完: template名、parameter名を補完
#     - F12: volumes.configMap.name → ConfigMapへジャンプ
#     - F12: volumes.secret.secretName → Secretへジャンプ
#
# [ ] エラー検出
#     - 存在しないtemplate名 → エラー表示
#     - 存在しないparameter名 → エラー表示
#     - 存在しないConfigMap/Secret → エラー表示
#     - 存在しないキー → エラー表示
#
# ========================================
