# ============================================================================
# inputs/outputs.parameters - パラメータの受け渡し
# ============================================================================
#
# 【テスト目的】
# - inputs.parametersの定義へのジャンプ機能
# - outputs.parametersの定義へのジャンプ機能
# - steps.outputs.parametersの参照解決
# - tasks.outputs.parametersの参照解決（DAG）
# - パラメータのホバー表示
# - クオートパターン（ダブル/シングル/なし）の動作確認
#
# 【動作確認方法】
# 1. F5でExtension Development Hostを起動
# 2. このファイルを開く
# 3. {{inputs.parameters.message}} (82行目) の "message" にカーソルを置いてF12
# 4. {{outputs.parameters.result}} (115行目) の "result" にカーソルを置いてF12
# 5. {{steps.generate.outputs.parameters.result}} (40行目) の "result" にカーソルを置いてF12
#
# 【期待動作】
# ✅ 82行目: 79行目の "- name: message" にジャンプ
# ✅ 115行目: 105行目の "- name: result" にジャンプ
# ✅ 40行目: 105行目の "- name: result" にジャンプ（steps経由）
# ✅ ホバーでパラメータの情報（デフォルト値、コメント等）が表示される
# ============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parameters-test-
  namespace: argo
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        # ---------------------------------------------------------------------
        # 【確認ポイント】outputs.parameters生成
        # generate-output テンプレートがパラメータを出力
        # ---------------------------------------------------------------------
        - - name: generate
            template: generate-output

        # ---------------------------------------------------------------------
        # 【確認ポイント】steps.outputs.parameters参照
        # 操作: {{steps.generate.outputs.parameters.result}} の "result" にカーソルを置いてF12
        # 期待: 105行目の "- name: result" にジャンプ
        # ---------------------------------------------------------------------
        - - name: consume
            template: consume-output
            arguments:
              parameters:
                - name: data
                  value: "{{steps.generate.outputs.parameters.result}}"

    # -------------------------------------------------------------------------
    # 【確認ポイント】outputs.parametersの定義とクオートパターン
    # -------------------------------------------------------------------------
    - name: generate-output
      outputs:
        parameters:
          # ダブルクオートで定義（通常の使用方法）
          - name: result
            valueFrom:
              path: "/tmp/result.txt"
          # シングルクオートで定義（パス指定など）
          - name: status
            valueFrom:
              path: '/tmp/status.txt'
          # クオートなしで定義
          - name: count
            valueFrom:
              path: /tmp/count.txt
      script:
        image: alpine:latest
        command: [sh]
        source: |
          echo "42" > /tmp/result.txt
          echo "success" > /tmp/status.txt
          echo "10" > /tmp/count.txt
          # 自テンプレート内での参照パターン
          echo "Result: {{outputs.parameters.result}}"
          echo 'Status: {{outputs.parameters.status}}'
          echo Count: {{outputs.parameters.count}}

    # -------------------------------------------------------------------------
    # 【確認ポイント】inputs.parametersの定義とクオートパターン
    # 操作: {{inputs.parameters.message}} の "message" にカーソルを置いてF12
    # 期待: 79行目の "- name: message" にジャンプ
    # -------------------------------------------------------------------------
    - name: consume-output
      inputs:
        parameters:
          # ダブルクオートのデフォルト値
          - name: data
            value: "default-data"
          # シングルクオートのデフォルト値
          - name: config
            value: 'default-config'
          # クオートなしのデフォルト値（数値）
          - name: timeout
            value: 30
      container:
        image: alpine:latest
        command: [sh, -c]
        args:
          - |
            echo "Data: {{inputs.parameters.data}}"
            echo 'Config: {{inputs.parameters.config}}'
            echo Timeout: {{inputs.parameters.timeout}}

---
# ============================================================================
# DAGでのparameters参照
# ============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-parameters-test-
  namespace: argo
spec:
  entrypoint: dag-main
  templates:
    - name: dag-main
      dag:
        tasks:
          - name: task-producer
            template: dag-producer

          # ---------------------------------------------------------------------
          # 【確認ポイント】tasks.outputs.parameters参照（ダブルクオート）
          # 操作: {{tasks.task-producer.outputs.parameters.output}} の "output" にカーソルを置いてF12
          # 期待: 139行目の "- name: output" にジャンプ
          # ---------------------------------------------------------------------
          - name: task-consumer-double
            template: dag-consumer
            dependencies: [task-producer]
            arguments:
              parameters:
                - name: data
                  value: "{{tasks.task-producer.outputs.parameters.output}}"

          # シングルクオートパターン
          - name: task-consumer-single
            template: dag-consumer
            dependencies: [task-producer]
            arguments:
              parameters:
                - name: data
                  value: '{{tasks.task-producer.outputs.parameters.output}}'

    - name: dag-producer
      outputs:
        parameters:
          - name: output
            valueFrom:
              path: /tmp/output.txt
      script:
        image: alpine:latest
        command: [sh]
        source: echo "dag-result" > /tmp/output.txt

    - name: dag-consumer
      inputs:
        parameters:
          - name: data
      container:
        image: alpine:latest
        command: [echo]
        args: ["Data: {{inputs.parameters.data}}"]
