# ============================================================================
# inputs/outputs.artifacts - アーティファクトの受け渡し
# ============================================================================
#
# 【テスト目的】
# - inputs.artifactsの定義へのジャンプ機能
# - outputs.artifactsの定義へのジャンプ機能
# - steps.outputs.artifactsの参照解決
# - tasks.outputs.artifactsの参照解決（DAG）
# - アーティファクトのホバー表示
#
# 【動作確認方法】
# 1. F5でExtension Development Hostを起動
# 2. このファイルを開く
# 3. {{inputs.artifacts.input-file}} (75行目) の "input-file" にカーソルを置いてF12
# 4. {{outputs.artifacts.output-file}} (61行目) の "output-file" にカーソルを置いてF12
# 5. {{steps.generate.outputs.artifacts.output-file}} (36行目) の "output-file" にカーソルを置いてF12
#
# 【期待動作】
# ✅ 75行目: 69行目の "- name: input-file" にジャンプ
# ✅ 61行目: 50行目の "- name: output-file" にジャンプ
# ✅ 36行目: 50行目の "- name: output-file" にジャンプ（steps経由）
# ✅ ホバーでアーティファクトの情報（path、コメント等）が表示される
# ============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifacts-test-
  namespace: argo
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: generate
            template: generate-artifact

        # ---------------------------------------------------------------------
        # 【確認ポイント】steps.outputs.artifacts参照
        # 操作: {{steps.generate.outputs.artifacts.output-file}} の "output-file" にカーソルを置いてF12
        # 期待: 50行目の "- name: output-file" にジャンプ
        # ---------------------------------------------------------------------
        - - name: consume
            template: consume-artifact
            arguments:
              artifacts:
                - name: input-file
                  from: "{{steps.generate.outputs.artifacts.output-file}}"

    # -------------------------------------------------------------------------
    # 【確認ポイント】outputs.artifactsの定義
    # 操作: {{outputs.artifacts.output-file}} の "output-file" にカーソルを置いてF12
    # 期待: 50行目の "- name: output-file" にジャンプ
    # -------------------------------------------------------------------------
    - name: generate-artifact
      outputs:
        artifacts:
          - name: output-file
            path: /tmp/output.txt
          - name: log-file
            path: /tmp/log.txt
      script:
        image: alpine:latest
        command: [sh]
        source: |
          echo "Generated content" > /tmp/output.txt
          echo "Log" > /tmp/log.txt
          # 自テンプレート内での参照
          echo "Output artifact: {{outputs.artifacts.output-file}}"
          echo "Log artifact: {{outputs.artifacts.log-file}}"

    # -------------------------------------------------------------------------
    # 【確認ポイント】inputs.artifactsの定義
    # 操作: {{inputs.artifacts.input-file}} の "input-file" にカーソルを置いてF12
    # 期待: 69行目の "- name: input-file" にジャンプ
    # -------------------------------------------------------------------------
    - name: consume-artifact
      inputs:
        artifacts:
          - name: input-file
            path: /tmp/input.txt
      container:
        image: alpine:latest
        command: [sh, -c]
        args:
          # 注: 実際のArgoではパス (/tmp/input.txt) を直接使用します
          # ここでは定義へのジャンプ機能確認のため、変数参照形式も記載
          - |
            echo "Reading artifact at: {{inputs.artifacts.input-file}}"
            cat /tmp/input.txt

---
# ============================================================================
# DAGでのartifacts参照
# ============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-artifacts-test-
  namespace: argo
spec:
  entrypoint: dag-main
  templates:
    - name: dag-main
      dag:
        tasks:
          - name: task-generate
            template: generate-artifact

          # ---------------------------------------------------------------------
          # 【確認ポイント】tasks.outputs.artifacts参照
          # 操作: {{tasks.task-generate.outputs.artifacts.result-file}} の "result-file" にカーソルを置いてF12
          # 期待: 119行目の "- name: result-file" にジャンプ
          # ---------------------------------------------------------------------
          - name: task-consume
            template: consume-artifact
            dependencies: [task-generate]
            arguments:
              artifacts:
                - name: input-file
                  from: "{{tasks.task-generate.outputs.artifacts.result-file}}"

    - name: generate-artifact
      outputs:
        artifacts:
          - name: result-file
            path: /tmp/result.txt
      script:
        image: alpine:latest
        command: [sh]
        source: echo "dag-data" > /tmp/result.txt

    - name: consume-artifact
      inputs:
        artifacts:
          - name: input-file
            path: /tmp/input.txt
      container:
        image: alpine:latest
        command: [cat]
        args: [/tmp/input.txt]
