# ============================================================================
# 基本的なWorkflow - ローカルテンプレートとsteps構造
# ============================================================================
#
# 【テスト目的】
# - ローカルテンプレートの定義と参照のジャンプ機能
# - steps構造での順次実行
# - template参照の解決
#
# 【動作確認方法】
# 1. F5でExtension Development Hostを起動
# 2. このファイルを開く
# 3. template: local-hello (25行目) にカーソルを置いてF12
#
# 【期待動作】
# ✅ 33行目の "- name: local-hello" にジャンプ
# ✅ ホバーで "container: alpine:latest, command: echo" などの情報が表示される
# ============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: basic-workflow-
  namespace: argo
spec:
  entrypoint: main
  templates:
    # ---------------------------------------------------------------------
    # 【確認ポイント】ローカルテンプレート参照のジャンプ
    # 操作: template: local-hello にカーソルを置いてF12
    # 期待: 33行目の "- name: local-hello" にジャンプ
    # ---------------------------------------------------------------------
    - name: main
      steps:
        - - name: step-hello
            template: local-hello
        - - name: step-goodbye
            template: local-goodbye

    # ---------------------------------------------------------------------
    # 【定義】ローカルテンプレート
    # 上の "template: local-hello" からジャンプされる先
    # ---------------------------------------------------------------------
    - name: local-hello
      container:
        image: alpine:latest
        command: [echo]
        args: ["Hello from local template!"]

    - name: local-goodbye
      container:
        image: alpine:latest
        command: [echo]
        args: ["Goodbye!"]
