# ============================================================================
# outputs.result - スクリプト実行結果の取得
# ============================================================================
#
# 【テスト目的】
# - outputs.resultの参照解決（script/scriptorテンプレート）
# - steps.outputs.resultの参照
# - tasks.outputs.resultの参照（DAG）
# - resultのホバー表示
#
# 【動作確認方法】
# 1. F5でExtension Development Hostを起動
# 2. このファイルを開く
# 3. {{steps.run-script.outputs.result}} (41行目) の "result" にカーソルを置いてF12
# 4. {{tasks.task-script.outputs.result}} (99行目) の "result" にカーソルを置いてF12
#
# 【期待動作】
# ✅ 41行目: 51行目のscript-runnerテンプレート（scriptセクション）にジャンプ
# ✅ 99行目: 107行目のscript-runnerテンプレート（scriptセクション）にジャンプ
# ✅ ホバーでスクリプト情報（言語、実行内容等）が表示される
#
# 【outputs.resultの説明】
# - scriptまたはscriptorテンプレートの標準出力が自動的にresultとして保存される
# - outputs.resultは明示的な定義が不要
# - スクリプトの最後のprint/echoの内容が結果となる
# ============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: output-result-test-
  namespace: argo
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: run-script
            template: script-runner

        # ---------------------------------------------------------------------
        # 【確認ポイント】steps.outputs.result参照
        # 操作: {{steps.run-script.outputs.result}} の "result" にカーソルを置いてF12
        # 期待: 51行目のscript-runnerテンプレート（scriptセクション）にジャンプ
        # ---------------------------------------------------------------------
        - - name: use-result
            template: print-result
            arguments:
              parameters:
                - name: data
                  value: "{{steps.run-script.outputs.result}}"

    # スクリプト結果を出力するテンプレート
    - name: script-runner  # JSONデータを生成
      script:
        image: python:3.9
        command: [python]
        source: |
          import json
          result = {"status": "success", "count": 42}
          # 最後のprintの内容がoutputs.resultとなる
          print(json.dumps(result))

    - name: print-result
      inputs:
        parameters:
          - name: data
      container:
        image: alpine:latest
        command: [echo]
        args: ["Result: {{inputs.parameters.data}}"]

---
# ============================================================================
# DAGでのoutputs.result参照
# ============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-result-test-
  namespace: argo
spec:
  entrypoint: dag-main
  templates:
    - name: dag-main
      dag:
        tasks:
          - name: task-script
            template: script-runner

          # ---------------------------------------------------------------------
          # 【確認ポイント】tasks.outputs.result参照
          # 操作: {{tasks.task-script.outputs.result}} の "result" にカーソルを置いてF12
          # 期待: 107行目のscript-runnerテンプレート（scriptセクション）にジャンプ
          # ---------------------------------------------------------------------
          - name: task-use-result
            template: print-result
            dependencies: [task-script]
            arguments:
              parameters:
                - name: data
                  value: "{{tasks.task-script.outputs.result}}"

    # DAG用スクリプトテンプレート
    - name: script-runner  # 文字列を出力
      script:
        image: python:3.9
        command: [python]
        source: print("dag-result")

    - name: print-result
      inputs:
        parameters:
          - name: data
      container:
        image: alpine:latest
        command: [echo]
        args: ["{{inputs.parameters.data}}"]
