# =============================================================================
# workflow-dag.yaml — DAG構造の動作確認
# =============================================================================
#
# 確認できること:
#   - DAG tasks[] でのテンプレート参照
#   - dependencies による依存関係指定
#   - ローカルテンプレート参照 + templateRef の混在
#
# テスト分類: Cluster（依存: workflow-template.yaml）
# =============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-workflow-
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          # --- ローカルテンプレート参照 ---
          - name: task-a
            template: step-a

          # --- ローカルテンプレート参照（task-aに依存） ---
          - name: task-b
            template: step-b
            dependencies: [task-a]

          # --- templateRef参照（task-aに依存） ---
          - name: task-c
            templateRef:
              name: shared-templates
              template: hello
            dependencies: [task-a]

          # --- task-b, task-c 両方に依存 ---
          - name: task-d
            templateRef:
              name: shared-templates
              template: whalesay
            dependencies: [task-b, task-c]
            arguments:
              parameters:
                - name: message
                  value: "DAG completed!"

    # --- ローカルテンプレート定義 ---
    - name: step-a
      container:
        image: alpine:latest
        command: [echo]
        args: ["Step A"]

    - name: step-b
      container:
        image: alpine:latest
        command: [echo]
        args: ["Step B"]
