# ============================================================================
# templateRef - WorkflowTemplate/ClusterWorkflowTemplate参照
# ============================================================================
#
# 【テスト目的】
# - WorkflowTemplateへの参照のジャンプ機能
# - ClusterWorkflowTemplateへの参照のジャンプ機能
# - templateRef解決とホバー表示
#
# 【動作確認方法】
# 1. F5でExtension Development Hostを起動
# 2. このファイルを開く
# 3. template: hello (29行目) にカーソルを置いてF12
# 4. template: cluster-hello (39行目) にカーソルを置いてF12
#
# 【期待動作】
# ✅ 29行目: workflow-template.yaml の "- name: hello" にジャンプ
# ✅ 39行目: cluster-workflow-template.yaml の "- name: cluster-hello" にジャンプ
# ✅ ホバーでテンプレートの情報が表示される
#
# 【注意】
# このWorkflowを実行するには、以下のリソースが必要です:
# - WorkflowTemplate "hello-world-template" (workflow-template.yaml)
# - ClusterWorkflowTemplate "cluster-hello-template" (cluster-workflow-template.yaml)
# ============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: templateref-test-
  namespace: argo
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        # ---------------------------------------------------------------------
        # 【確認ポイント】WorkflowTemplate参照のジャンプ
        # 操作: template: hello にカーソルを置いてF12
        # 期待: workflow-template.yaml の "- name: hello" にジャンプ
        # ---------------------------------------------------------------------
        - - name: step-from-template
            templateRef:
              name: hello-world-template
              template: hello

        # ---------------------------------------------------------------------
        # 【確認ポイント】ClusterWorkflowTemplate参照のジャンプ
        # 操作: template: cluster-hello にカーソルを置いてF12
        # 期待: cluster-workflow-template.yaml の "- name: cluster-hello" にジャンプ
        # ---------------------------------------------------------------------
        - - name: step-from-cluster-template
            templateRef:
              name: cluster-hello-template
              template: cluster-hello
              clusterScope: true
