# =============================================================================
# workflow-templateref.yaml — templateRef参照の動作確認
# =============================================================================
#
# 確認できること:
#   - templateRef で WorkflowTemplate のテンプレートにジャンプ
#   - templateRef + clusterScope: true で ClusterWorkflowTemplate にジャンプ
#
# テスト分類: Cluster（依存: workflow-template.yaml, cluster-workflow-template.yaml）
# =============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: templateref-workflow-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        # --- templateRef でWorkflowTemplateのhelloにジャンプ ---
        - - name: call-hello
            templateRef:
              name: shared-templates
              template: hello
        # --- templateRef でWorkflowTemplateのwhalesayにジャンプ ---
        - - name: call-whalesay
            templateRef:
              name: shared-templates
              template: whalesay
            arguments:
              parameters:
                - name: message
                  value: "Hello via templateRef!"
        # --- clusterScope: true でClusterWorkflowTemplateにジャンプ ---
        - - name: call-cluster-hello
            templateRef:
              name: cluster-shared-templates
              template: cluster-hello
              clusterScope: true
        # --- clusterScope: true でClusterWorkflowTemplateのjobにジャンプ ---
        - - name: call-cluster-job
            templateRef:
              name: cluster-shared-templates
              template: cluster-job
              clusterScope: true
