# ============================================================================
# DAG構造 - 並列実行と依存関係
# ============================================================================
#
# 【テスト目的】
# - DAG構造でのテンプレート参照のジャンプ機能
# - tasks参照の解決
# - 並列実行とdependencies指定
#
# 【動作確認方法】
# 1. F5でExtension Development Hostを起動
# 2. このファイルを開く
# 3. template: echo-task (28行目) にカーソルを置いてF12
# 4. template: whalesay (43行目) にカーソルを置いてF12
#
# 【期待動作】
# ✅ 28行目: 53行目の "- name: echo-task" にジャンプ
# ✅ 43行目: workflow-template.yaml の "- name: whalesay" にジャンプ
# ✅ ホバーでテンプレートの情報が表示される
#
# 【DAG構造の説明】
# - task-a: 最初に実行（依存なし）
# - task-b: task-a完了後に実行（dependencies: [task-a]）
# - task-c: task-a完了後に実行（dependencies: [task-a]）、templateRef使用
# task-bとtask-cは並列実行される
# ============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-workflow-
  namespace: argo
spec:
  entrypoint: dag-main
  templates:
    - name: dag-main
      dag:
        tasks:
          # ---------------------------------------------------------------------
          # 【確認ポイント】DAGでのローカルテンプレート参照
          # 操作: template: echo-task にカーソルを置いてF12
          # 期待: 53行目の "- name: echo-task" にジャンプ
          # ---------------------------------------------------------------------
          - name: task-a
            template: echo-task
            arguments:
              parameters:
                - name: message
                  value: "Task A"

          - name: task-b
            template: echo-task
            dependencies: [task-a]
            arguments:
              parameters:
                - name: message
                  value: "Task B (after A)"

          # ---------------------------------------------------------------------
          # 【確認ポイント】DAGでのtemplateRef参照
          # 操作: template: whalesay にカーソルを置いてF12
          # 期待: workflow-template.yaml の "- name: whalesay" にジャンプ
          # ---------------------------------------------------------------------
          - name: task-c
            templateRef:
              name: hello-world-template
              template: whalesay
            dependencies: [task-a]
            arguments:
              parameters:
                - name: message
                  value: "Task C from templateRef (after A)"

    # ---------------------------------------------------------------------
    # 【定義】ローカルテンプレート
    # 上の "template: echo-task" からジャンプされる先
    # ---------------------------------------------------------------------
    - name: echo-task
      inputs:
        parameters:
          - name: message
      container:
        image: alpine:latest
        command: [echo]
        args: ["{{inputs.parameters.message}}"]
