# ============================================================================
# item変数 - withItems/withParamによるループ処理
# ============================================================================
#
# 【テスト目的】
# - item変数のホバー表示
# - item.propertyの参照解決
# - withItemsソース定義へのジャンプ機能
# - withParamソース定義へのジャンプ機能
# - スカラー値、オブジェクト、数値の各パターン
#
# 【動作確認方法】
# 1. F5でExtension Development Hostを起動
# 2. このファイルを開く
# 3. {{item}} (60行目) にカーソルを置いてホバー
# 4. {{item.name}} (79行目) の "name" にカーソルを置いてF12
# 5. withItems: (63行目) にカーソルを置いてホバー
#
# 【期待動作】
# ✅ 60行目: ホバーで "現在のループアイテム（文字列）" などの説明が表示される
# ✅ 79行目: 82行目のwithItemsオブジェクト定義（{ name: "item-a", ... }）にジャンプ
# ✅ 63行目: ホバーでwithItemsの値リストが表示される
# ✅ item, item.name, item.countなど各パターンで適切な情報が表示される
# ============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: item-test-
  namespace: argo
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        # ---------------------------------------------------------------------
        # 【確認ポイント】withItems - スカラー値（文字列）
        # 操作: {{item}} にカーソルを置いてホバー
        # 期待: "現在のループアイテム（文字列）" の説明が表示される
        # ---------------------------------------------------------------------
        - - name: process-strings
            template: echo-item
            arguments:
              parameters:
                - name: message
                  value: "{{item}}"
            withItems:
              - "apple"
              - "banana"
              - "cherry"

        # ---------------------------------------------------------------------
        # 【確認ポイント】withItems - オブジェクト値
        # 操作: {{item.name}} の "name" にカーソルを置いてF12
        # 期待: 82行目のwithItemsオブジェクト定義にジャンプ
        # 操作: {{item.count}} の "count" にカーソルを置いてF12
        # 期待: 82行目のwithItemsオブジェクト定義にジャンプ
        # ---------------------------------------------------------------------
        - - name: process-objects
            template: echo-props
            arguments:
              parameters:
                - name: name
                  value: "{{item.name}}"
                - name: count
                  value: "{{item.count}}"
            withItems:
              - { name: "item-a", count: 1 }
              - { name: "item-b", count: 2 }
              - { name: "item-c", count: 3 }

        # ---------------------------------------------------------------------
        # 【確認ポイント】withItems - 数値
        # ---------------------------------------------------------------------
        - - name: process-numbers
            template: echo-item
            arguments:
              parameters:
                - name: message
                  value: "Number: {{item}}"
            withItems:
              - 10
              - 20
              - 30

    - name: echo-item
      inputs:
        parameters:
          - name: message
      container:
        image: alpine:latest
        command: [echo]
        args: ["{{inputs.parameters.message}}"]

    - name: echo-props
      inputs:
        parameters:
          - name: name
          - name: count
      container:
        image: alpine:latest
        command: [sh, -c]
        args:
          - |
            echo "Name: {{inputs.parameters.name}}"
            echo "Count: {{inputs.parameters.count}}"

---
# ============================================================================
# withParam - パラメータから配列を取得
# ============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: withparam-test-
  namespace: argo
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: items-json
        value: '["red", "green", "blue"]'
  templates:
    - name: main
      steps:
        # ---------------------------------------------------------------------
        # 【確認ポイント】withParam - ワークフローパラメータから取得
        # 操作: withParam: の行にカーソルを置いてF12
        # 期待: 113行目の "- name: items-json" にジャンプ
        # ---------------------------------------------------------------------
        - - name: process-from-param
            template: echo-item
            arguments:
              parameters:
                - name: message
                  value: "Color: {{item}}"
            withParam: "{{workflow.parameters.items-json}}"

        # ---------------------------------------------------------------------
        # 【確認ポイント】withParam - ステップ出力から取得
        # ---------------------------------------------------------------------
        - - name: generate-list
            template: generate-items

        - - name: process-generated
            template: echo-item
            arguments:
              parameters:
                - name: message
                  value: "Generated: {{item}}"
            # 操作: withParam: の行にカーソルを置いてF12
            # 期待: 159行目の "- name: items" にジャンプ
            withParam: "{{steps.generate-list.outputs.parameters.items}}"

    - name: echo-item
      inputs:
        parameters:
          - name: message
      container:
        image: alpine:latest
        command: [echo]
        args: ["{{inputs.parameters.message}}"]

    - name: generate-items
      outputs:
        parameters:
          - name: items
            valueFrom:
              path: /tmp/items.json
      script:
        image: alpine:latest
        command: [sh]
        source: |
          echo '["one", "two", "three"]' > /tmp/items.json

---
# ============================================================================
# DAGでのitem変数
# ============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-item-test-
  namespace: argo
spec:
  entrypoint: dag-main
  templates:
    - name: dag-main
      dag:
        tasks:
          # ---------------------------------------------------------------------
          # 【確認ポイント】DAG taskでのwithItems - スカラー値
          # ---------------------------------------------------------------------
          - name: parallel-process
            template: echo-item
            arguments:
              parameters:
                - name: message
                  value: "DAG item: {{item}}"
            withItems:
              - "task-a"
              - "task-b"
              - "task-c"

          # ---------------------------------------------------------------------
          # 【確認ポイント】DAG taskでのwithItems - オブジェクト
          # ---------------------------------------------------------------------
          - name: parallel-objects
            template: echo-props
            dependencies: [parallel-process]
            arguments:
              parameters:
                - name: name
                  value: "{{item.name}}"
                - name: count
                  value: "{{item.count}}"
            withItems:
              - { name: "obj-1", count: 100 }
              - { name: "obj-2", count: 200 }

    - name: echo-item
      inputs:
        parameters:
          - name: message
      container:
        image: alpine:latest
        command: [echo]
        args: ["{{inputs.parameters.message}}"]

    - name: echo-props
      inputs:
        parameters:
          - name: name
          - name: count
      container:
        image: alpine:latest
        command: [echo]
        args: ["Name={{inputs.parameters.name}}, Count={{inputs.parameters.count}}"]
